config/routes.rb
Rails.application.routes.draw do
  get 'samples/index'

  get 'samples/service'

  get 'samples/portfolio'

  get 'samples/team'

  get 'samples/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def index
  end

  def service
  end

  def portfolio
  end

  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer
	============================================= -->
    <footer>
        <div class="container">
            <h1>Rise</h1>
            <div class="social">
                <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
                <a href="#"><i class="fa fa-dribbble fa-2x"></i></a>
            </div>
            <h6>&copy; 2015 Rise.Development By BootstrapDev</h6>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<!-- Preloader ============================================= -->
    <div class="preloader"><i class="fa fa-circle-o-notch fa-spin fa-2x"></i></div>
    <!-- Header  ============================================= -->
    <section class="main-header">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img src="/assets/logo/logo.png" class="img-responsive" alt="logo"></a>
                </div>
                <div class="collapse navbar-collapse text-center" id="bs-example-navbar-collapse-1">
                    <div class="col-md-8 col-xs-12 nav-wrap">
                        <ul class="nav navbar-nav">
                            <li><%= link_to 'Home', samples_index_path %></li>
                            <li><%= link_to 'Services', samples_service_path %></li>
                            <li><%= link_to 'Works', samples_portfolio_path %></li>
                            <li><%= link_to 'About', samples_team_path %></li>
                            <li><%= link_to 'Contact', samples_contact_path %></li>
                        </ul>
                    </div>
                    <div class="social-media hidden-sm hidden-xs">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
      </section>

app/views/layouts/_import_assets.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">

<!-- Bootstrap Css -->
<link href="/assets/bootstrap.min.css" rel="stylesheet">

<!-- Style -->
<link href="/assets/owl.carousel.css" rel="stylesheet">
<link href="/assets/owl.theme.css" rel="stylesheet">
<link href="/assets/owl.transitions.css" rel="stylesheet">
<link href="/assets/lightbox.css" rel="stylesheet">
<link href="/assets/et-line-font-style.css" rel="stylesheet">
<link href="/assets/animate.css" rel="stylesheet">
<link href="/assets/main.css" rel="stylesheet">
<!-- Icons Font -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

app/views/layouts/_plugin_js_imports.html.erb
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/custom.js"></script>
    <!-- JS PLUGINS -->
    <script src="/assets/owl.carousel.min.js"></script>
    <script src="/assets/jquery.easing.min.js"></script>
    <script src="/assets/jquery.waypoints.min.js"></script>
    <script src="/assets/jquery.countTo.js"></script>
    <script src="/assets/jquery.inview.min.js"></script>
    <script src="/assets/lightbox.min.js"></script>
    <script src="/assets/wow.min.js"></script>
    <!-- GOOGLE MAP -->
    <!-- <script src="https://maps.googleapis.com/maps/api/js"></script> -->
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyA6nPcLP-6qZloY926VLNCgzaz69oT_apw&libraries=places&sensor=false"></script>

app/views/layouts/_rails_defaluts.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>WebMechanic</title>
    <%= render 'layouts/rails_defaults'%>
    <%= render 'layouts/import_assets'%>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/plugin_js_imports'%>
  </body>
</html>

app/views/samples/contact.html.erb
<!-- Contact Us
============================================= -->
  <section id="contact">
      <div class="container">
          <h2>Contact Us</h2>
          <hr class="sep">
          <p>Get In Touch</p>
          <div class="col-md-6 col-md-offset-3 wow fadeInUp" data-wow-delay=".3s">
              <form>
                  <div class="form-group">
                      <input type="text" class="form-control" id="Name" placeholder="Name">
                  </div>
                  <div class="form-group">
                      <input type="text" class="form-control" id="Email" placeholder="Email">
                  </div>
                  <div class="form-group">
                      <textarea class="form-control" rows="3" placeholder="Message"></textarea>
                  </div>
                  <a href="#" class="btn-block">Send</a>
              </form>
          </div>
      </div>
  </section>
  <!-- Google Map
============================================= -->
  <div id="map"></div>

app/views/samples/index.html.erb
<div id="owl-hero" class="owl-carousel owl-theme">
    <div class="item" style="background-image: url(/assets/sliders/Slide.jpg)">
        <div class="caption">
            <h6>Branding / Design / Creativty</h6>
            <h1>We Are <span>Rise</span></h1>
            <a class="btn btn-transparent" href="#">Learn More</a><a class="btn btn-light" href="#">Buy Now</a>
        </div>
    </div>
    <div class="item" style="background-image: url(/assets/sliders/Slide2.jpg)">
        <div class="caption">
            <h6>Branding / Design / Creativty</h6>
            <h1>Creative <span>Design</span></h1>
            <a class="btn btn-transparent" href="#">Learn More</a><a class="btn btn-light" href="#">Buy Now</a>
        </div>
    </div>
    <div class="item" style="background-image: url(/assets/sliders/Slide3.jpg)">
        <div class="caption">
            <h6>Branding / Design / Creativty</h6>
            <h1>Clean <span>Code</span></h1>
            <a class="btn btn-transparent" href="#">Learn More</a><a class="btn btn-light" href="#">Buy Now</a>
        </div>
    </div>
</div>

<!-- Welcome
============================================= -->
<section id="welcome">
    <div class="container">
        <h2>Welcome To <span>Rise</span></h2>
        <hr class="sep">
        <p>Make Yourself At Home Don't Be Shy</p>
        <img class="img-responsive center-block wow fadeInUp" data-wow-delay=".3s" src="/assets/welcome/logo.png" alt="logo">
    </div>
</section>

app/views/samples/portfolio.html.erb
<!-- Portfolio
	============================================= -->
    <section id="portfolio">
        <div class="container-fluid">
            <h2>Our Work</h2>
            <hr class="sep">
            <p>Showcase Your Amazing Work With Us</p>
            <div class="row">
                <div class="col-lg-4 col-sm-6 wow fadeInUp" data-wow-delay=".3s">
                    <a class="portfolio-box" href="/assets/portfolio/1.jpg" data-lightbox="image-1" data-title="Your caption">
                        <img src="/assets/portfolio/1.jpg" class="img-responsive" alt="1">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6 wow fadeInUp" data-wow-delay=".3s">
                    <a href="/assets/portfolio/2.jpg" class="portfolio-box" data-lightbox="image-2" data-title="Your caption">
                        <img src="/assets/portfolio/2.jpg" class="img-responsive" alt="2">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6 wow fadeInUp" data-wow-delay=".3s">
                    <a href="/assets/portfolio/3.jpg" class="portfolio-box" data-lightbox="image-3" data-title="Your caption">
                        <img src="/assets/portfolio/3.jpg" class="img-responsive" alt="3">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6 wow fadeInUp" data-wow-delay=".3s">
                    <a href="/assets/portfolio/4.jpg" class="portfolio-box" data-lightbox="image-4" data-title="Your caption">
                        <img src="/assets/portfolio/4.jpg" class="img-responsive" alt="4">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6 wow fadeInUp" data-wow-delay=".3s">
                    <a href="/assets/portfolio/5.jpg" class="portfolio-box" data-lightbox="image-5" data-title="Your caption">
                        <img src="/assets/portfolio/5.jpg" class="img-responsive" alt="5">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6 wow fadeInUp" data-wow-delay=".3s">
                    <a href="/assets/portfolio/6.jpg" class="portfolio-box" data-lightbox="image-6" data-title="Your caption">
                        <img src="/assets/portfolio/6.jpg" class="img-responsive" alt="6">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- Work Process
	============================================= -->
    <section id="work-process">
        <div class="container">
            <h2>Work Process</h2>
            <hr class="sep">
            <p>What Happen In The Background</p>
            <div class="row wow fadeInUp" data-wow-delay=".3s">
                <div class="col-lg-3">
                    <span class="icon-chat"></span>
                    <h4>1.Discuss</h4>
                </div>
                <div class="col-lg-3">
                    <span class="icon-circle-compass"></span>
                    <h4>2.Sketch</h4>
                </div>
                <div class="col-lg-3">
                    <span class="icon-browser"></span>
                    <h4>3.Make</h4>
                </div>
                <div class="col-lg-3">
                    <span class="icon-global"></span>
                    <h4>4.Publish</h4>
                </div>
            </div>
        </div>
    </section>
    <!-- Some Fune Facts
	============================================= -->
    <section id="fun-facts">
        <div class="container">
            <h2>Some Fun Facts </h2>
            <hr class="light-sep">
            <p>Fun Facts</p>
            <div class="row wow fadeInUp" data-wow-delay=".3s">
                <div class="col-lg-3">
                    <span class="icon-happy"></span>
                    <h2 class="number timer">367</h2>
                    <h4>Happy Clients</h4>
                </div>
                <div class="col-lg-3">
                    <span class="icon-trophy"></span>
                    <h2 class="number timer">150</h2>
                    <h4>Project Done</h4>
                </div>
                <div class="col-lg-3">
                    <span class="icon-wine"></span>
                    <h2 class="number timer">121</h2>
                    <h4>Glass Of Wine</h4>
                </div>
                <div class="col-lg-3">
                    <span class="icon-documents"></span>
                    <h2 class="number timer">10000</h2>
                    <h4>Lines Of Code</h4>
                </div>
            </div>
        </div>
    </section>

app/views/samples/service.html.erb
<!-- Services
============================================= -->
<section id="services">
    <div class="container">
        <h2>What We Do</h2>
        <hr class="light-sep">
        <p>We Can Do Crazy Things</p>
        <div class="services-box">
            <div class="row wow fadeInUp" data-wow-delay=".3s">
                <div class="col-md-4">
                    <div class="media-left"><span class="icon-lightbulb"></span></div>
                    <div class="media-body">
                        <h3>Creative Design</h3>
                        <p>Fringilla augue at maximus vestibulum. Nam pulvinar vitae neque et porttitor. Praesent sed nisi eleifend.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="media-left"><span class="icon-mobile"></span></div>
                    <div class="media-body">
                        <h3>Bootstrap</h3>
                        <p>Fringilla augue at maximus vestibulum. Nam pulvinar vitae neque et porttitor. Praesent sed nisi eleifend.</p>
                    </div>

                </div>
                <div class="col-md-4">
                    <div class="media-left"><span class="icon-compass"></span></div>
                    <div class="media-body">
                        <h3>Sass &amp; Compass</h3>
                        <p>Fringilla augue at maximus vestibulum. Nam pulvinar vitae neque et porttitor. Praesent sed nisi eleifend.</p>
                    </div>

                </div>

                <div class="row wow fadeInUp" data-wow-delay=".6s">
                    <div class="col-md-4">
                        <div class="media-left"><span class="icon-adjustments"></span></div>
                        <div class="media-body">
                            <h3>Easy To Customize</h3>
                            <p>Fringilla augue at maximus vestibulum. Nam pulvinar vitae neque et porttitor. Praesent sed nisi eleifend.</p>
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="media-left"><span class="icon-tools"></span></div>
                        <div class="media-body">
                            <h3>Photoshop</h3>
                            <p>Fringilla augue at maximus vestibulum. Nam pulvinar vitae neque et porttitor. Praesent sed nisi eleifend.</p>
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="media-left"><span class="icon-wallet"></span></div>
                        <div class="media-body">
                            <h3>Money Saver</h3>
                            <p>Fringilla augue at maximus vestibulum. Nam pulvinar vitae neque et porttitor. Praesent sed nisi eleifend.</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/samples/team.html.erb
<!-- Team
============================================= -->
  <section id="team">
      <div class="container">
          <h2>Our Team</h2>
          <hr class="sep">
          <p>Designers Behind This Work</p>
          <div class="row wow fadeInUp" data-wow-delay=".3s">
              <div class="col-md-4">
                  <div class="team">
                      <img class="img-responsive center-block" src="/assets/team/MariaDoe.jpg" alt="1">
                      <h4>Maria Doe</h4>
                      <p>Designer</p>
                      <div class="team-social-icons">
                          <a href="#"><i class="fa fa-facebook"></i></a>
                          <a href="#"><i class="fa fa-twitter"></i></a>
                          <a href="#"><i class="fa fa-dribbble"></i></a>
                      </div>
                  </div>
              </div>
              <div class="col-md-4">
                  <div class="team">
                      <img class="img-responsive center-block" src="/assets/team/JasonDoe.jpg" alt="2">
                      <h4>Jason Doe</h4>
                      <p>Developer</p>
                      <div class="team-social-icons">
                          <a href="#"><i class="fa fa-facebook"></i></a>
                          <a href="#"><i class="fa fa-twitter"></i></a>
                          <a href="#"><i class="fa fa-dribbble"></i></a>
                      </div>
                  </div>
              </div>
              <div class="col-md-4">
                  <div class="team">
                      <img class="img-responsive center-block" src="/assets/team/MikeDoe.jpg" alt="3">
                      <h4>Mike Doe</h4>
                      <p>Photographer</p>
                      <div class="team-social-icons">
                          <a href="#"><i class="fa fa-facebook"></i></a>
                          <a href="#"><i class="fa fa-twitter"></i></a>
                          <a href="#"><i class="fa fa-dribbble"></i></a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>